# Generated by Django 2.1.15 on 2022-02-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcprice',
            name='price',
            field=models.FloatField(max_length=255),
        ),
    ]
